### ISSUE TITLE
Problems about training referring image segmentation

### ISSUE THREAD

**Issue by fawnliu** [ubc-vision/RefTR#1]
Hello, thank you very much for releasing the source code.  After training the detection task and saving the model to `exps/refcoco/r101_det/checkpoint_best.pth`, I intend to train the segmentation task further, but I encounter an error. Can you tell me how to solve this error?

The error occurs when I run `GPUS_PER_NODE=2  tools/run_dist_launch.sh   2  configs/refcoco/RefTR_refcoco_101.sh`.
The content of `RefTR_refcoco_101.sh` is
```
EXP_DIR=exps/refcoco/r101
python -u main_vg.py \
    --pretrained_model "exps/refcoco/r101_det/checkpoint_best.pth"\
    --num_feature_levels 1\
    --masks\
    --lr 1e-5\
    --lr_mask_branch_proj 10\
    --dataset refcoco_unc\
    --train_split train\
    --test_split val testA testB\
    --dec_layers 6\
    --backbone resnet101\
    --aux_loss \
    --img_size 640\
    --max_img_size 640\
    --epochs 40\
    --lr_drop 30\
    --output_dir ${EXP_DIR} \
```

This is the error information.

```
+ GPUS=2
+ RUN_COMMAND=configs/refcoco/RefTR_refcoco_101.sh
+ '[' 2 -lt 8 ']'
+ GPUS_PER_NODE=2
+ MASTER_ADDR=127.0.0.1
+ MASTER_PORT=29500
+ NODE_RANK=0
+ let NNODES=GPUS/GPUS_PER_NODE
+ python ./tools/launch.py --nnodes 1 --node_rank 0 --master_addr 127.0.0.1 --master_port 29500 --nproc_per_node 2 configs/refcoco/RefTR_refcoco_101.sh
+ PY_ARGS=
+ EXP_DIR=exps/refcoco/r101_det
+ EXP_DIR=exps/refcoco/r101
+ python -u main_vg.py --pretrained_model exps/refcoco/r101_det/checkpoint_best.pth --num_feature_levels 1 --masks --lr 1e-5 --lr_mask_branch_proj 10 --dataset refcoco_unc --train_split train --test_split val testA testB --dec_layers 6 --backbone resnet101 --aux_loss --img_size 640 --max_img_size 640 --epochs 40 --lr_drop 30 --output_dir exps/refcoco/r101
+ PY_ARGS=
+ EXP_DIR=exps/refcoco/r101_det
+ EXP_DIR=exps/refcoco/r101
+ python -u main_vg.py --pretrained_model exps/refcoco/r101_det/checkpoint_best.pth --num_feature_levels 1 --masks --lr 1e-5 --lr_mask_branch_proj 10 --dataset refcoco_unc --train_split train --test_split val testA testB --dec_layers 6 --backbone resnet101 --aux_loss --img_size 640 --max_img_size 640 --epochs 40 --lr_drop 30 --output_dir exps/refcoco/r101
| distributed init (rank 0): env://
backend=nccl, init_method=env://, world_size=2, rank=0
| distributed init (rank 1): env://
backend=nccl, init_method=env://, world_size=2, rank=1
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
git:
  sha: N/A, status: clean, branch: N/A

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Model dim: 256
Language model dim: 768
Using multi phrase loss
number of params: 174134685
Steps per training epoch:  3769
Using pretrained MODEL exps/refcoco/r101_det/checkpoint_best.pth to init the model.
Unexpected keys:  []
Missing keys:  ['bbox_attention.q_linear.weight', 'bbox_attention.q_linear.bias', 'bbox_attention.k_linear.weight', 'bbox_attention.k_linear.bias', 'mask_head.lay1.weight', 'mask_head.lay1.bias', 'mask_head.gn1.weight', 'mask_head.gn1.bias', 'mask_head.lay2.weight', 'mask_head.lay2.bias', 'mask_head.gn2.weight', 'mask_head.gn2.bias', 'mask_head.lay3.weight', 'mask_head.lay3.bias', 'mask_head.gn3.weight', 'mask_head.gn3.bias', 'mask_head.lay4.weight', 'mask_head.lay4.bias', 'mask_head.gn4.weight', 'mask_head.gn4.bias', 'mask_head.lay5.weight', 'mask_head.lay5.bias', 'mask_head.gn5.weight', 'mask_head.gn5.bias', 'mask_head.out_lay.weight', 'mask_head.out_lay.bias', 'mask_head.adapter1.weight', 'mask_head.adapter1.bias', 'mask_head.adapter2.weight', 'mask_head.adapter2.bias', 'mask_head.adapter3.weight', 'mask_head.adapter3.bias']
Start training
Traceback (most recent call last):
  File "main_vg.py", line 439, in <module>
    main(args)
  File "main_vg.py", line 371, in main
    model, criterion, data_loader_train, optimizer, lr_scheduler, device, epoch, args.clip_max_norm)
  File "/mnt/RefTR-main/engine_vg.py", line 41, in train_one_epoch
    loss_dict = criterion(outputs, targets)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/RefTR-main/models/criterion.py", line 186, in forward
    losses.update(self.get_loss(loss, outputs, targets, num_boxes, **kwargs))
  File "/mnt/RefTR-main/models/criterion.py", line 164, in get_loss
    return loss_map[loss](outputs, targets, num_boxes, **kwargs)
  File "/mnt/RefTR-main/models/criterion.py", line 150, in loss_boxes
    box_ops.box_cxcywh_to_xyxy(target_boxes)))
  File "/mnt/RefTR-main/util/box_ops.py", line 66, in generalized_box_iou
    assert (boxes2[:, 2:] >= boxes2[:, :2]).all()
AssertionError
```

**Comment by jojo23333** [comment]
Hi, this probably indicates that there is something wrong with your annotation that the ground truth box passed in is not in the form of cxcywh, may I know which annotation file you are using for multi-task training?

**Comment by fawnliu** [comment]
Thanks for your quick response. I use `data/unc/unc_val.pth` as annotation file for training grounding task, and no errors are reported when training this task. The same annotation file is utilized for multi-task training, but the error occurs. So I'm really puzzled by this error.

I notice some differences between the dataset loader of grounding and segmentation task.
In the ReferSegDataset for segmentation, [`bbox = np.array(bbox, dtype=int)`](https://github.com/ubc-vision/RefTR/blob/4129e906cb3b0587746839af3a8bc1a5d21a39e4/datasets/grounding_datasets/refer_dataset.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L263) 
In the ReferDataset for groundin, [`bbox[2], bbox[3] = bbox[0]+bbox[2], bbox[1]+bbox[3]`](https://github.com/ubc-vision/RefTR/blob/4129e906cb3b0587746839af3a8bc1a5d21a39e4/datasets/grounding_datasets/resc_refer_dataset.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L129)

I insert this line `bbox[2], bbox[3] = bbox[0]+bbox[2], bbox[1]+bbox[3]` after `bbox = np.array(bbox, dtype=int)` in the ReferSegDataset. The error does not occur any more.

**Comment by jojo23333** [comment]
Sorry for the bug, I use a different annotation file for segmentation since the original annotation do not contain mask ground truth, I'll update the script for that part soon.
